- src/main/__tests__/index.test.js
- src/main/index.js
- src/settings/__tests__/browser-settings.test.js
- src/settings/browser-settings.css
- src/settings/browser-settings.js
> ✨: Tabs can be disabled

- src/main/__tests__/index.test.js
- src/main/index.js
BrowserView autoResize is not enough (apparently) to keep the browser views within the content bounds of the main window.
This improvement on the resize window event, resizes the browser views so that they all fit the width and the last browser view fits the remaining height.
Before this fix, part of the browser views were hidden (or the opposite, not filling the window) when considerable resizing occurred in the main window.
> 🐞: Main window resize updates browser views content bounds

- README.md
- docs/Keyboard-shortcuts.md
- docs/Roadmap.md
- package-lock.json
- package.json
- src/chrome-tabs/__tests__/browser-chrome-tabs.test.js
- src/chrome-tabs/browser-chrome-tabs.js
- src/chrome-tabs/index.html
- src/chrome-tabs/index.js
- src/chrome-tabs/preload.js
- src/main/__tests__/index.test.js
- src/main/index.js
- src/settings/__tests__/index.test.js
- src/settings/index.js
- Completely based on Preact
- chrome-tabs external dependency only used for styles
- Ditched draggabilly
- Probably fixed issue related with draggabilly on MacOS
- Fixed edge-case bugs when loading invalid settings
> 🧹 Refactored chrome-tabs module

- package-lock.json
- package.json
- src/tab-manager/__tests__/browser-mediadevices-shim.test.js
- src/tab-manager/__tests__/browser-notification-shim.test.js
- src/tab-manager/__tests__/preload.test.js
- src/tab-manager/browser-mediadevices-shim.js
- src/tab-manager/preload.js
Screen/Window to share can be selected from a list of windows
in an embedded popup in the current webapplication window
Clicking the window thumbnail shares that screen/window
Clicking on the surrounding areas cancels the selection
> ✨: Screen can be shared

- src/tab-manager/__tests__/redirect.test.js
- src/tab-manager/redirect.js
Just added a few IM accounts I know (fixes #42)
All of them seems to be working (if no third-party 2FA configured).
> Add support for Skype, MS Teams and Webex Teams

- src/tab-manager/__tests__/redirect.test.js
- src/tab-manager/redirect.js
> 🐞: Fix login to Tweet Deck is now possible

- package-lock.json
- package.json
- src/tab-manager/__tests__/browser-notification-shim.test.js
- src/tab-manager/__tests__/index.test.js
> ⬆ Bump dev dependencies

- .github/workflows/publish-npm.yml
- .github/workflows/publish-windows.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- README.md
- build-config/electronim.nuspec
- package-lock.json
- package.json
> ⬆ Bump electron to 19.0.14

- package-lock.json
- package.json
- src/settings/__tests__/browser-settings.test.js
> ⬆ Bump and fix production dependencies

- src/chrome-tabs/index.html
- src/chrome-tabs/preload.js
- src/components/__tests__/styles.test.js
- src/components/index.js
- src/components/styles.js
- src/help/__tests/preload.test.js
- src/help/index.html
- src/help/preload.js
- src/settings/index.html
- src/settings/preload.js
> 🐛 npx execution should load styles

- src/help/__tests/browser-help.test.js
- src/help/browser-help.css
- src/help/browser-help.js
- src/help/preload.js
- src/settings/browser-settings.js
> ♻️ Help has top bar (consistent UX)

- src/chrome-tabs/index.html
- src/help/index.html
- src/settings/index.html
> 🔒️ Fix Electron Security Warning (Insecure Content-Security-Policy)

- package-lock.json
- package.json
- src/chrome-tabs/index.js
- src/help/index.js
- src/main/index.js
- src/settings/index.js
- src/tab-manager/index.js
> ⬆ Bump electron to 20.1.1

- src/components/__tests__/styles.test.js
- src/components/styles.js
- src/help/__tests/preload.test.js
> ♻️ refactor addStylesheet

- src/settings/browser-settings.js
> 🐛 fix url validation

- package-lock.json
- package.json
> 🤖 Remove unused electron-packager config and dependency

- .github/workflows/tests.yml
> 🤖 publish packaged artifacts of SNAPSHOTS to GH

- src/settings/browser-settings.css
> 💄 replaced enabled dictionaries settings layout

- .eslintrc
- package.json
- src/components/README.md
- src/constants/index.js
- src/main/index.js
- src/settings/__tests__/index.test.js
- src/settings/__tests__/settings.browser.test.mjs
- src/settings/index.js
- src/settings/settings.browser.mjs
- src/settings/settings.common.browser.mjs
- src/settings/settings.reducer.browser.mjs
- src/settings/settings.spell-check.browser.mjs
- src/spell-check/__tests__/index.test.js
- src/spell-check/index.js
- src/tab-manager/__tests__/index.test.js
- src/tab-manager/__tests__/preload.spell-check.test.js
- src/tab-manager/__tests__/preload.test.js
- src/tab-manager/index.js
- src/tab-manager/preload.js
- src/tab-manager/preload.spell-check.js
> Optional support for Electron's built-in native spellchecker

- src/settings/settings.browser.css
> 💄 dictionaries listed in top-bottom left-right order

- README.md
> 📚 Badge with Chocolatey package version

- src/main/__tests__/index.test.js
- src/main/index.js
> 🐛 resize/maximize works properly on Linux

- package-lock.json
- package.json
> ⬆ Bump electron to 21.0.0

- package.json
- src/browser-window/__tests__/index.test.js
- src/browser-window/index.js
> Chore: disable dialog auto resize #128

- src/chrome-tabs/index.js
> chrome-tabs auto resize is disabled

- src/tab-manager/__tests__/redirect.test.js
- src/tab-manager/redirect.js
> ✨ support for GoDaddy OAuth specific URLs

- src/help/index.js
> Removed native web open option pref

- src/chrome-tabs/index.js
> Removed deprecated nativeWindowOpen option

- src/tab-manager/__tests__/index.test.js
- src/tab-manager/index.js
- Added reload option in the context menu
Relates to #114
> Refresh button for each tab

- src/__tests__/electron.js
- src/__tests__/index.js
- src/spell-check/index.js
- src/tab-manager/__tests__/context-menu.test.js
- src/tab-manager/__tests__/index.test.js
- src/tab-manager/context-menu.js
- src/tab-manager/index.js
> ✨ context-menu with clipboard functionality

- package.json
- src/__tests__/electron.js
- src/__tests__/setup-jest.js
- src/chrome-tabs/__tests__/check-for-updates.test.js
- src/chrome-tabs/__tests__/chrome-tabs.browser.test.mjs
- src/chrome-tabs/__tests__/index.test.js
- src/chrome-tabs/check-for-updates.js
- src/chrome-tabs/chrome-tabs.browser.mjs
- src/chrome-tabs/chrome-tabs.reducer.browser.mjs
- src/chrome-tabs/index.js
- src/constants/index.js
- src/main/__tests__/index.test.js
Fixes #97 
ElectronIM will check for updates every 30 minutes
> ✨ menu button displays up arrow when new version available

- docs/Keyboard-shortcuts.md
- src/__tests__/electron.js
- src/constants/index.js
- src/main/__tests__/index.test.js
- src/main/__tests__/keyboard-shortcuts.test.js
- src/main/index.js
- src/main/keyboard-shortcuts.js
> ✨ Full screen mode can be toggled pressing F11

- docs/Keyboard-shortcuts.md
- src/browser-window/__tests__/keyboard-shortcuts.test.js
- src/browser-window/keyboard-shortcuts.js
- src/components/switch.mjs
- src/constants/index.js
- src/main/__tests__/global-listeners.test.js
- src/main/index.js
- src/tab-manager/__tests__/index.test.js
- src/tab-manager/index.js
> ✨ Ctrl+[1-9] / Cmd+[1-9] switches to tab at position

- src/__tests__/electron.js
- src/components/icon.mjs
- src/constants/index.js
- src/main/__tests__/global-listeners.test.js
- src/main/__tests__/index.test.js
- src/main/__tests__/init-browser-versions.test.js
- src/main/index.js
- src/settings/__tests__/index.test.js
- src/settings/__tests__/settings.browser.mjs
- src/settings/__tests__/settings.browser.test.mjs
- src/settings/__tests__/settings.other.browser.test.mjs
- src/settings/index.js
- src/settings/settings.browser.mjs
- src/settings/settings.other.browser.mjs
- src/settings/settings.reducer.browser.mjs
- src/tab-manager/__tests__/index.test.js
- src/tab-manager/index.js
- src/tray/__tests__/index.test.js
- src/tray/index.js
> ✨ initial support for Tray

- .github/workflows/publish.yml
- .github/workflows/tests.yml
- build-config/electronim.desktop
- build-config/electronim.spec
- package.json
Initial files to be able to deploy to [Fedora copr](https://copr.fedorainfracloud.org/coprs/)
Packages for v0.0.87 have already been published manually: https://copr.fedorainfracloud.org/coprs/manusa/electronim
Relates to #241
> RPM source files

- src/tab-manager/__tests__/redirect.test.js
- src/tab-manager/redirect.js
> ✨ support for Zoho OAuth specific URLs

- src/tab-manager/__tests__/redirect.test.js
- src/tab-manager/redirect.js
Relates to #254 
> Trying to download a file from slack doesn't work either. Instead is spawns a browser page and requests to login into the web interface.
Should be fixed now
> 🐛 Slack files downloaded from ElectronIM

- src/components/top-app-bar.mjs
- src/main/index.js
- src/settings/__tests__/settings.browser.test.mjs
- src/settings/settings.browser.mjs
- src/settings/settings.reducer.browser.mjs
> ✨ settings cannot be cancelled when initial setup

- src/browser-window/__tests__/keyboard-shortcuts.test.js
- src/browser-window/keyboard-shortcuts.js
> 🐛 Escape key works on applications running in service tabs

- src/__tests__/electron.js
- src/__tests__/index.test.js
- src/index.js
- src/main/__tests__/quit.test.js
- src/main/index.js
- src/main/quit.js
> ✨ cache storage cleared upon app quit

- .github/workflows/publish.yml
- package.json
> build: add apple silicon

- src/spell-check/dictionary.renderer/dictionary.worker.js
Added a compare function to avoid sorting elements alphabetically, as said in issue #335
> Added a compare function to avoid sorting elements alphabetically

- src/main/quit.js
issue no: #345 
Changed a code so that void is returned.
> Changed so that void is returned

- src/user-agent/__tests__/index.test.js
- src/user-agent/index.js
> 🐛 latest Chrome release retrieved from versionhistory.googleapis.com

- src/main/__tests__/index.test.js
- src/main/index.js
- src/tab-manager/__tests__/index.test.js
- src/tab-manager/index.js
> 🐛 updated tab order respected while traversing tabs

- src/main/__tests__/init-browser-versions.test.js
- src/main/index.js
- src/tab-manager/index.js
- src/user-agent/__tests__/index.test.js
- src/user-agent/index.js
Allows easier transition to BaseWindow and Electron 30
> ♻️ user-agent for webContents

- README.md
- build-config/electronim.nuspec
- package-lock.json
- package.json
- src/settings/settings.browser.css
> ⬆ Bump electron to 33.2.1

- src/__tests__/electron.js
- src/settings/settings.spell-check.browser.mjs
- src/spell-check/index.js
- https://github.com/electron/electron/issues/44336
- https://github.com/manusa/electronim/issues/463
- https://github.com/manusa/electronim/issues/449
> 🐛 force native spell check until Electron issue is fixed

- package-lock.json
- package.json
- webpack.js
Seems like there is some legacy dependencies to sass and scss for webpack processing.
> fix(deps): remove unneeded sass-related dependencies
